//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSuPhongBan
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien_ChucVu
    {
        public int Id { get; set; }
        public string MaNhanVien { get; set; }
        public string MaChucVu { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
